Api/Controllers/AdminController.cs
using Api.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.Controllers
{
    public class AdminController : Controller
    {
        databaseContext object_Sql = new databaseContext();

        // GET: Admin
        public ActionResult AdminLogin()
        {
            return View();
        }

        // GET: Admin
        public ActionResult AdminZone()
        {
            return View();
        }

        // GET: Admin
        public ActionResult invalid()
        {
            return View();
        }





        [HttpPost]
        public ActionResult loginAuthenticate(Login user)
        {
            //Pass the data to store the record into the table 

            DataTable tbl = new DataTable();
            tbl=object_Sql.CheckLogin("select * from LoginTable where UserName='" + user.userName + "'and Password='" + user.userPassword + "'");

            if (tbl.Rows.Count > 0)
            {
                return View("AdminZone");
            }
            else {
                return View("invalid");
            }



        }


    }
}

Api/Controllers/ProductController.cs
using Api.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.Controllers
{
    public class ProductController : Controller
    {
        WebApiEntities obj_databaseContext = new WebApiEntities();
        // GET: Product
        public ActionResult viewProduct()
        {
            return View(obj_databaseContext.ProductTables.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "id")] ProductTable product)
        {
            if (!ModelState.IsValid)
                return View();
            obj_databaseContext.ProductTables.Add(product);
            obj_databaseContext.SaveChanges();
            return RedirectToAction("viewProduct");

        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            var IdToEdit = (from m in obj_databaseContext.ProductTables where m.id == id select m).First();
            return View(IdToEdit);
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(ProductTable IdToEdit)
        {

            var orignalRecord = (from m in obj_databaseContext.ProductTables where m.id == IdToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            obj_databaseContext.Entry(orignalRecord).CurrentValues.SetValues(IdToEdit);

            obj_databaseContext.SaveChanges();
            return RedirectToAction("viewProduct");


        }

        // GET: Product/Delete/5
        public ActionResult Delete(ProductTable IdToDel)
        {
            var d = obj_databaseContext.ProductTables.Where(x => x.id == IdToDel.id).FirstOrDefault();
            obj_databaseContext.ProductTables.Remove(d);
            obj_databaseContext.SaveChanges();
            return RedirectToAction("viewProduct");
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Api/Controllers/UserController.cs
using Api.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        WebApiEntities obj_databaseContext = new WebApiEntities();

        public ActionResult AllUser()
        {
            return View(obj_databaseContext.UserTables.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            var IdToEdit = (from m in obj_databaseContext.UserTables where m.ID == id select m).First();
            return View(IdToEdit);
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(UserTable IdToEdit)
        {

            var orignalRecord = (from m in obj_databaseContext.UserTables where m.ID == IdToEdit.ID select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            obj_databaseContext.Entry(orignalRecord).CurrentValues.SetValues(IdToEdit);

            obj_databaseContext.SaveChanges();
            return RedirectToAction("AllUser");

        }

        // GET: User/Delete/5
        public ActionResult Delete(UserTable IdToDel)
        {

            var d = obj_databaseContext.UserTables.Where(x => x.ID == IdToDel.ID).FirstOrDefault();
            obj_databaseContext.UserTables.Remove(d);
            obj_databaseContext.SaveChanges();
            return RedirectToAction("AllUser");
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Api/Views/Admin/AdminLogin.cshtml
@{
    ViewBag.Title = "AdminLogin";
}


<br /><br /><br /><br />
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" action="loginAuthenticate">

                <div class="form-group">
                    <label>User Name </label>
                    <input type="text" name="userName" id="userName" required class="form-control" />


                </div>



                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="userPassword" id="userPassword" required class="form-control" />


                </div>





                <div class="form-group">
                    <input type="submit" class="btn btn-primary" />


                </div>





            </form>

        </div>
    </div>
</div>

Api/Views/Admin/AdminZone.cshtml
@{
    ViewBag.Title = "AdminZone";
}


<div class="container">
    <div class="col-md-12">
        <h1> Welcome to the Admin Area  </h1>


        <h3> <a href="@Url.Action("viewProduct","Product")">Product Record </a></h3>

        <h3> <a href="@Url.Action("AllUser","User")">Register User Record </a></h3>


        <h3> <a href="@Url.Action("viewFeedback","Home")">Feed Back </a></h3>

        <a href="@Url.Action("Index","Home")" class="btn btn-warning">Back to Main </a>

    </div>

</div>

Api/Views/Admin/invalid.cshtml
@{
    ViewBag.Title = "invalid";
}

<div class="container">
    <div class="col-md-12">
        <h1> Invalid User Name or Password </h1>
        <a href="@Url.Action("AdminLogin","Admin")">Back to Login </a>
    </div>
</div>